name: "Terraform Module Build"

on:
  pull_request:
    types: 
      - closed

permissions:
  id-token: write
  contents: write

jobs:
  build:
    if: >-
      (github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login == 'sentania-labs')
      && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        ref: main
        fetch-depth: 0
    
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@c360518fb8131e99795f8208f8a6105ceca55ec2 # 1.64.0
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }} 
        WITH_V: true
    
    - name: Generate release    
      uses: marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1 # latest
      with:
        automatic_release_tag: ${{ steps.tag.outputs.tag }}
        repo_token: ${{ secrets.REPO_ACCESS_TOKEN }}  
        prerelease: false
        draft: false
